/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author mehzanazkhan
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbInfo1 = new javax.swing.JLabel();
        stockPanel1 = new javax.swing.JPanel();
        lbStock1 = new javax.swing.JLabel();
        pendingPanel4 = new javax.swing.JPanel();
        lbPending4 = new javax.swing.JLabel();
        salesPanel2 = new javax.swing.JPanel();
        lbSales2 = new javax.swing.JLabel();
        accountPanel3 = new javax.swing.JPanel();
        lbAccount3 = new javax.swing.JLabel();

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setText("Dashboard");

        lbInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lbInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo1.setText("Welcome to InfoPharma Ordering System");

        stockPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbStock1.setText("Total Stock Items");

        javax.swing.GroupLayout stockPanel1Layout = new javax.swing.GroupLayout(stockPanel1);
        stockPanel1.setLayout(stockPanel1Layout);
        stockPanel1Layout.setHorizontalGroup(
            stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbStock1)
                .addContainerGap(253, Short.MAX_VALUE))
        );
        stockPanel1Layout.setVerticalGroup(
            stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbStock1)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pendingPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbPending4.setText("Pending Orders");

        javax.swing.GroupLayout pendingPanel4Layout = new javax.swing.GroupLayout(pendingPanel4);
        pendingPanel4.setLayout(pendingPanel4Layout);
        pendingPanel4Layout.setHorizontalGroup(
            pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPending4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pendingPanel4Layout.setVerticalGroup(
            pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbPending4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        salesPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbSales2.setText("Today's Sales");

        javax.swing.GroupLayout salesPanel2Layout = new javax.swing.GroupLayout(salesPanel2);
        salesPanel2.setLayout(salesPanel2Layout);
        salesPanel2Layout.setHorizontalGroup(
            salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSales2)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        salesPanel2Layout.setVerticalGroup(
            salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbSales2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accountPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbAccount3.setText("Active Customers");

        javax.swing.GroupLayout accountPanel3Layout = new javax.swing.GroupLayout(accountPanel3);
        accountPanel3.setLayout(accountPanel3Layout);
        accountPanel3Layout.setHorizontalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAccount3)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        accountPanel3Layout.setVerticalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbAccount3)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lbTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbInfo1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stockPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pendingPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(240, 240, 240))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbInfo1)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pendingPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel3;
    private javax.swing.JLabel lbAccount3;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbPending4;
    private javax.swing.JLabel lbSales2;
    private javax.swing.JLabel lbStock1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pendingPanel4;
    private javax.swing.JPanel salesPanel2;
    private javax.swing.JPanel stockPanel1;
    // End of variables declaration//GEN-END:variables
}
